<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../SDVE/Datos/*.cs" Link="Datos/%(Filename)%(Extension)" />
    <Compile Include="../../SDVE/Login/Sesion.cs" Link="Login/Sesion.cs" />
    <Compile Include="../../SDVE/Login/RegistroParticipacion.cs" Link="Login/RegistroParticipacion.cs" />
    <Compile Include="../../SDVE/Votaciones/DatosVotacion.cs" Link="Votaciones/DatosVotacion.cs" />
    <Compile Include="../../SDVE/Conteo/*.cs" Link="Conteo/%(Filename)%(Extension)" />
    <None Include="../../SDVE/Datos/alumnos.csv" Link="Datos/alumnos.csv" CopyToOutputDirectory="Always" />
    <None Include="../../SDVE/Datos/votantes.csv" Link="Datos/votantes.csv" CopyToOutputDirectory="Always" />
    <None Include="../../SDVE/Datos/votos.csv" Link="Datos/votos.csv" CopyToOutputDirectory="Always" />
    <None Include="../../SDVE/Datos/participacion.csv" Link="Datos/participacion.csv" CopyToOutputDirectory="Always" />
    <None Include="../../SDVE/Datos/convocatorias.csv" Link="Datos/convocatorias.csv" CopyToOutputDirectory="Always" />
    <None Include="../../SDVE/Datos/candidatos.csv" Link="Datos/candidatos.csv" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
